#!/usr/bin/env python3
"""Bake the attributed PS5 wordmark into a tiny alpha mask; no runtime decoder."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
image = Image.open(ROOT / 'artwork/ps5-logo.png').convert('RGBA').resize((320, 70), Image.Resampling.LANCZOS)
alpha = image.getchannel('A').tobytes()
header = '// Generated by tools/build-platform-logo.py. Sony PS5 wordmark; see artwork/README.md.\n'
header += '#pragma once\n#include <array>\nnamespace botty::art {\n'
header += 'inline constexpr std::array<unsigned char,22400> ps5Logo{{\n'
header += '\n'.join(','.join(str(b) for b in alpha[i:i+80])+',' for i in range(0,len(alpha),80))
header += '\n}};\n}\n'
(ROOT / 'src/platform_logo.hpp').write_text(header)
