#!/usr/bin/env python3
"""Bake the bundled OFL font to native alpha masks; Pillow is a build-only tool."""
from pathlib import Path
import hashlib
from PIL import Image, ImageDraw, ImageFont
ROOT=Path(__file__).resolve().parents[1]
font_path=ROOT/'vendor/manrope/Manrope.ttf'
data=bytearray(); faces=[]
for size in [20,24,28,32,44,60,76]:
    font=ImageFont.truetype(str(font_path),size)
    font.set_variation_by_axes([600 if size>=32 else 500])
    glyphs=[]
    for code in range(32,127):
        c=chr(code); left,top,right,bottom=font.getbbox(c)
        width,height=right-left,bottom-top
        image=Image.new('L',(max(1,width),max(1,height)))
        ImageDraw.Draw(image).text((-left,-top),c,font=font,fill=255)
        glyphs.append((len(data),width,height,left,top,round(font.getlength(c))))
        if width and height:data.extend(image.tobytes())
    faces.append((size,glyphs))
(ROOT/'assets/ui-font.bin').write_bytes(data)
header='''// Generated by tools/build-font.py from Manrope (SIL OFL 1.1).
#pragma once
#include <array>
#include <cstdint>
namespace botty::font {
struct Glyph { unsigned offset; unsigned short width,height; short left,top,advance; };
struct Face { unsigned size; std::array<Glyph,95> glyphs; };
'''
header+=f'inline constexpr unsigned dataSize={len(data)};\n'
header+='inline constexpr std::array<Face,7> faces{{\n'
for size,glyphs in faces:
    header+=f'    {{{size}, {{{{\n'
    header+=''.join('        {'+','.join(map(str,g))+'},\n' for g in glyphs)
    header+='    }}},\n'
header+='}};\n}\n'
(ROOT/'src/font_data.hpp').write_text(header)
print('Font bytes:',len(data),'source SHA256:',hashlib.sha256(font_path.read_bytes()).hexdigest())
